# Generated by Django 3.1.4 on 2021-08-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_company_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='image',
            new_name='logo',
        ),
    ]
